# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-09 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191108_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='aaa'),
        ),
    ]
