# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-16 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0005_cart_sub_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=120)),
                ('shipping_total', models.DecimalField(decimal_places=2, default=9.99, max_digits=50)),
                ('order_toatl', models.DecimalField(decimal_places=2, default=9.99, max_digits=50)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='created', max_length=120)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.Cart')),
            ],
        ),
    ]
